# Generated by Django 5.2.6 on 2025-09-15 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='owner',
            fields=[
                ('Model', models.CharField(max_length=10)),
                ('Car_no', models.IntegerField(primary_key=True, serialize=False)),
                ('Quality', models.CharField(max_length=10)),
                ('Year_prod', models.IntegerField()),
                ('Colour', models.CharField(max_length=10)),
            ],
        ),
    ]
